---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/featured
  label: Featured
  create: all
  match: "**/*"
- type: directory
  path: content/jobs
  label: Jobs
  create: all
  match: "**/*"
  new_doc_ext: index.md
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
- type: heading
  label: Work Experience
- type: heading
  label: Projects
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
